# NumPy Tutorial

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6]
arr_lst = np.array(lst)
print(arr_lst)
print(type(arr_lst))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr_lst.shape

(6,)

In [4]:
# Creating a 2D array

list_1 = [1,3,4,6,3]
list_2 = [2,5,6,9,0]
list_3 = [7,5,8,2,4]

#creating an array
array_2D = np.array([list_1,list_2,list_3])
array_2D

array([[1, 3, 4, 6, 3],
       [2, 5, 6, 9, 0],
       [7, 5, 8, 2, 4]])

In [5]:
type(array_2D)

numpy.ndarray

In [6]:
array_2D.shape

(3, 5)

In [7]:
array_2D.reshape(5,3)

array([[1, 3, 4],
       [6, 3, 2],
       [5, 6, 9],
       [0, 7, 5],
       [8, 2, 4]])

In [8]:
array_2D

array([[1, 3, 4, 6, 3],
       [2, 5, 6, 9, 0],
       [7, 5, 8, 2, 4]])

In [9]:
# Indexing

# indexing in numpy array also starts from 0

print(array_2D[:,:]) # This will return complete array

[[1 3 4 6 3]
 [2 5 6 9 0]
 [7 5 8 2 4]]


In [10]:
'''
Requirement: 
array([[1, 3],
       [2, 5]])
'''

array_2D[0:2,0:2] # This achieves our requirement

array([[1, 3],
       [2, 5]])

In [11]:
'''
Requirement: 
array([[4, 6, 3],
       [6, 9, 0]])
'''
array_2D[0:2,2:]

array([[4, 6, 3],
       [6, 9, 0]])

In [12]:
array_2D[0:2,0:5:2] #slicing alternate elements in column

array([[1, 4, 3],
       [2, 6, 0]])

In [13]:
array_2D[0::2,0:5] #slicing alternate elements in row

array([[1, 3, 4, 6, 3],
       [7, 5, 8, 2, 4]])

In [14]:
'''
Requirement: 
array([[6, 3],
       [2, 4]])
'''
array_2D[::2,3:]

array([[6, 3],
       [2, 4]])

In [15]:
# np.arange() and np.linspace()

np.arange(1, 10) # arange() returns the numbers from start to stop and optional step

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1, 10, 2) # start, stop, [step]

array([1, 3, 5, 7, 9])

In [17]:
#linspace

    np.linspace(1, 10, num =50, endpoint=False) # linspace equally divides the numbers from start to end. 
# num-> number of steps(spacing) and endpoint -> inclusion of end value (True/False)

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [18]:
np.linspace(1, 10, num =50, endpoint=False, retstep=True) # retstep = True/False returns spacing value

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]), 0.18)

In [19]:
# copy() function and broadcasting

arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2 = arr1 # Here arr1 and arr2 takes the same memory space
arr2
print("Array 1 before broadcasting: {}".format(arr1))
print("Array 2 before broadcasting: {}".format(arr2))

arr1[3:] = 100 #broadcasting

# since arr1 and arr2 takes the same memory space both are same (if you change one, other will change)

print("Array 1 after broadcasting: {}".format(arr1))

print("Array 2 after broadcasting: {}".format(arr2)) 

Array 1 before broadcasting: [1 2 3 4 5 6 7 8 9]
Array 2 before broadcasting: [1 2 3 4 5 6 7 8 9]
Array 1 after broadcasting: [  1   2   3 100 100 100 100 100 100]
Array 2 after broadcasting: [  1   2   3 100 100 100 100 100 100]


In [21]:
# copy() function

arr = np.linspace(2,10,5)
print ("Array 1 before copy: {}".format(arr))

array = arr.copy()
print ("Array 1 after copy: {}".format(arr))
print ("Array 2 after copy: {}".format(array))

arr[3:] = 100 #broadcasting

# since arr and array takes the different memory space (so changing one don't reflect other)

print("Array 1 after broadcasting: {}".format(arr))

print("Array 2 after broadcasting: {}".format(array)) 

Array 1 before copy: [ 2.  4.  6.  8. 10.]
Array 1 after copy: [ 2.  4.  6.  8. 10.]
Array 2 after copy: [ 2.  4.  6.  8. 10.]
Array 1 after broadcasting: [  2.   4.   6. 100. 100.]
Array 2 after broadcasting: [ 2.  4.  6.  8. 10.]


In [22]:
# some operations

a1 = np.linspace(2,10,5)
print(a1)
res = a1*2
print(a1*res)

[ 2.  4.  6.  8. 10.]
[  8.  32.  72. 128. 200.]


In [23]:
# Muliplying to np arrays
array1 = np.linspace(1,20,5)
array2 = np.linspace(2,30,5)
print(array1); print(array2)
print(array1*array2)

[ 1.    5.75 10.5  15.25 20.  ]
[ 2.  9. 16. 23. 30.]
[  2.    51.75 168.   350.75 600.  ]


In [24]:
# np.random function

print("Uniformly Distributed values {}".format(np.random.rand(1,10)))
print("Normally Distributed values {}".format(np.random.randn(1,10)))
print("Uniformly Distributed integers {}".format(np.random.randint(1,10)))
print("Uniformly Distributed floating number {}".format(np.random.ranf()))


Uniformly Distributed values [[0.38015179 0.11288521 0.12984728 0.05323637 0.76581742 0.67712407
  0.03255113 0.62059025 0.69191421 0.22948463]]
Normally Distributed values [[-1.1512685  -2.17786977  0.40854419  2.36922822  0.22878047 -0.84426531
  -0.53937923  0.48498113  1.96046081 -1.54994982]]
Uniformly Distributed integers 9
Uniformly Distributed floating number 0.8815568402483965


In [25]:
# random_sample

np.random.random_sample((5,))

array([0.78233071, 0.73302702, 0.33630434, 0.04260367, 0.06169165])